# Generated by Django 3.0.8 on 2020-09-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200831_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_user',
            new_name='user',
        ),
    ]
