# Generated by Django 3.0.8 on 2020-09-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200901_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
