# Generated by Django 3.0.8 on 2020-10-09 04:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200901_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=users.models.UserProfile.upload_image_to),
        ),
    ]
