# Generated by Django 3.0.8 on 2020-08-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20200821_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='med_treatment',
            field=models.CharField(default='random medical treatment', max_length=100, verbose_name='medical treatment'),
        ),
    ]
