# Generated by Django 3.0.8 on 2020-08-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20200824_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
