# Generated by Django 3.0.8 on 2020-08-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20200824_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='category',
            new_name='pet_category',
        ),
    ]
