# Generated by Django 3.0.8 on 2020-08-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20200825_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_category',
        ),
    ]
