# Generated by Django 3.0.8 on 2020-08-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_auto_20200828_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
