# Generated by Django 3.0.8 on 2020-09-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_auto_20200831_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='goal_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='pledged_amount',
            field=models.IntegerField(default=0),
        ),
    ]
