# Generated by Django 3.0.8 on 2020-09-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_auto_20200904_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.Pet'),
        ),
    ]
